/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assessments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Assessments
         * @description Assessment history, most recent first.
         */
        get: operations["list_assessments_api_v1_assessments_get"];
        put?: never;
        /** Create Assessment */
        post: operations["create_assessment_api_v1_assessments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assessments/{assessment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Assessment */
        get: operations["get_assessment_api_v1_assessments__assessment_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Tag Assessment
         * @description Attach a warehouse identifier so performance metrics can be joined to
         *     this assessment later. Does not affect scoring or its cache key.
         */
        patch: operations["tag_assessment_api_v1_assessments__assessment_id__patch"];
        trace?: never;
    };
    "/api/v1/brands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Brands */
        get: operations["list_brands_api_v1_brands_get"];
        put?: never;
        /** Create Brand */
        post: operations["create_brand_api_v1_brands_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/brands/{brand_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Brand */
        get: operations["get_brand_api_v1_brands__brand_id__get"];
        put?: never;
        post?: never;
        /** Delete Brand */
        delete: operations["delete_brand_api_v1_brands__brand_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/brands/{brand_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_api_v1_brands__brand_id__documents_get"];
        put?: never;
        /** Upload Document */
        post: operations["upload_document_api_v1_brands__brand_id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comparisons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Comparison
         * @description Score several variants of the same ad and rank them.
         */
        post: operations["create_comparison_api_v1_comparisons_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdMetadata
         * @description What the user tells us about where the ad will run.
         */
        AdMetadata: {
            /** Platform */
            platform: string;
            /** Industry */
            industry: string;
            /** Ad Type */
            ad_type: string;
        };
        /**
         * AdScorecard
         * @description The scoring contract.
         *
         *     Doubles as the provider output schema, so a provider physically cannot
         *     return a shape this application does not understand.
         */
        AdScorecard: {
            /**
             * Scores
             * @description One 0-10 score per criterion. All six are required.
             */
            scores: {
                [key: string]: number;
            };
            /** Overall Score */
            overall_score: number;
            /**
             * Feedback
             * @description A short paragraph of overall assessment.
             */
            feedback: string;
            /**
             * Recommendations
             * @description At most five concrete, actionable changes.
             */
            recommendations?: string[];
            /**
             * Citations
             * @description Filenames of the guidance passages the judgement rests on.
             */
            citations?: string[];
        };
        /**
         * Assessment
         * @description A complete assessment: what was asked, what was seen, what was judged.
         */
        Assessment: {
            /** Id */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            metadata: components["schemas"]["AdMetadata"];
            scorecard: components["schemas"]["AdScorecard"];
            visual_analysis: components["schemas"]["VisualAnalysis"];
            /** Context */
            context?: components["schemas"]["RetrievedChunk"][];
            /** Image Sha256 */
            image_sha256?: string | null;
            /**
             * Provider Info
             * @description Which models and prompt version produced this, for cache keying.
             */
            provider_info?: Record<string, never>;
            /**
             * External Ad Id
             * @description This assessment's identifier in the user's own data warehouse, so performance metrics pulled from there can be joined back to it. Set after the fact via PATCH, deliberately not part of build_cache_key: tagging an assessment must never invalidate its cached scorecard.
             */
            external_ad_id?: string | null;
        };
        /** Body_create_assessment_api_v1_assessments_post */
        Body_create_assessment_api_v1_assessments_post: {
            /**
             * Ad Image
             * Format: binary
             */
            ad_image: string;
            /** Platform */
            platform: string;
            /** Industry */
            industry: string;
            /** Ad Type */
            ad_type: string;
            /** Brand Id */
            brand_id?: string | null;
        };
        /** Body_create_comparison_api_v1_comparisons_post */
        Body_create_comparison_api_v1_comparisons_post: {
            /** Ad Images */
            ad_images: string[];
            /** Platform */
            platform: string;
            /** Industry */
            industry: string;
            /** Ad Type */
            ad_type: string;
            /** Brand Id */
            brand_id?: string | null;
        };
        /** Body_upload_document_api_v1_brands__brand_id__documents_post */
        Body_upload_document_api_v1_brands__brand_id__documents_post: {
            /**
             * Document
             * Format: binary
             */
            document: string;
        };
        /**
         * Brand
         * @description An advertiser whose own guidelines augment the global best practices.
         */
        Brand: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Document Count
             * @default 0
             */
            document_count: number;
        };
        /**
         * Comparison
         * @description Several variants of the same ad, judged together and ranked.
         */
        Comparison: {
            /** Id */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            metadata: components["schemas"]["AdMetadata"];
            /** Entries */
            entries: components["schemas"]["ComparisonEntry"][];
        };
        /**
         * ComparisonEntry
         * @description One variant's placement in a comparison.
         */
        ComparisonEntry: {
            /**
             * Rank
             * @description 1 is best.
             */
            rank: number;
            /**
             * Label
             * @description The uploaded filename, for identification.
             */
            label: string;
            assessment: components["schemas"]["Assessment"];
        };
        /** CreateBrandRequest */
        CreateBrandRequest: {
            /** Name */
            name: string;
        };
        /**
         * Criterion
         * @enum {string}
         */
        Criterion: "attention" | "clarity" | "targeting" | "cta" | "branding" | "value";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Knowledge Ready */
            knowledge_ready: boolean;
            /** Vision Provider */
            vision_provider: string;
            /** Scoring Provider */
            scoring_provider: string;
        };
        /**
         * KnowledgeDocument
         * @description One ingested brand document.
         */
        KnowledgeDocument: {
            /** Id */
            id: string;
            /** Brand Id */
            brand_id: string;
            /** Filename */
            filename: string;
            /** Content Sha256 */
            content_sha256: string;
            /** Chunk Count */
            chunk_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * RetrievedChunk
         * @description One passage of marketing guidance pulled from the knowledge store.
         */
        RetrievedChunk: {
            /** Text */
            text: string;
            /** Source */
            source: string;
            /** Chunk */
            chunk?: number | null;
            /** Brand Id */
            brand_id?: string | null;
        };
        /** TagAssessmentRequest */
        TagAssessmentRequest: {
            /**
             * External Ad Id
             * @description This assessment's identifier in your own data warehouse.
             */
            external_ad_id?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VisualAnalysis
         * @description Structured description of the creative, produced by the vision model.
         */
        VisualAnalysis: {
            /**
             * Colors
             * @description Dominant colors, hex where legible.
             */
            colors?: string[];
            /**
             * Text
             * @description Key copy detected in the creative.
             * @default
             */
            text: string;
            /**
             * Layout
             * @description Composition and focal areas.
             * @default
             */
            layout: string;
            /**
             * Cta
             * @description Visible call-to-action text, empty if none.
             * @default
             */
            cta: string;
            /**
             * Insights
             * @description Short strength/risk observations.
             */
            insights?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_assessments_api_v1_assessments_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assessment"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_assessment_api_v1_assessments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_assessment_api_v1_assessments_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assessment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_assessment_api_v1_assessments__assessment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assessment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tag_assessment_api_v1_assessments__assessment_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagAssessmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assessment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_brands_api_v1_brands_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Brand"][];
                };
            };
        };
    };
    create_brand_api_v1_brands_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBrandRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Brand"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_brand_api_v1_brands__brand_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brand_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Brand"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_brand_api_v1_brands__brand_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brand_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_v1_brands__brand_id__documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brand_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeDocument"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_document_api_v1_brands__brand_id__documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brand_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_v1_brands__brand_id__documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_comparison_api_v1_comparisons_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_comparison_api_v1_comparisons_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comparison"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
