"""add data source connections and performance metrics

Revision ID: 20166c0cf015
Revises: 28f2d48538fa
Create Date: 2026-09-07 00:01:57.166024

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# Custom column types referenced by autogenerated migrations.
import backend.app.infra.db.types  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '20166c0cf015'
down_revision: str | Sequence[str] | None = '28f2d48538fa'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_source_connections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('dialect', sa.String(length=32), nullable=False),
    sa.Column('connection_uri_encrypted', sa.Text(), nullable=False),
    sa.Column('query_text_encrypted', sa.Text(), nullable=False),
    sa.Column('created_at', backend.app.infra.db.types.UtcDateTime(timezone=True), nullable=False),
    sa.Column('last_tested_at', backend.app.infra.db.types.UtcDateTime(timezone=True), nullable=True),
    sa.Column('last_test_ok', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('performance_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('connection_id', sa.String(length=36), nullable=False),
    sa.Column('external_ad_id', sa.String(length=128), nullable=False),
    sa.Column('ctr', sa.Float(), nullable=True),
    sa.Column('spend', sa.Float(), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('fetched_at', backend.app.infra.db.types.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['data_source_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('performance_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_performance_metrics_connection_id'), ['connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_performance_metrics_external_ad_id'), ['external_ad_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_performance_metrics_external_ad_id'))
        batch_op.drop_index(batch_op.f('ix_performance_metrics_connection_id'))

    op.drop_table('performance_metrics')
    op.drop_table('data_source_connections')
    # ### end Alembic commands ###
