"""add external_ad_id to assessments

Revision ID: 28f2d48538fa
Revises: 6451082f08e8
Create Date: 2026-09-06 23:49:03.462848

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# Custom column types referenced by autogenerated migrations.
import backend.app.infra.db.types  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '28f2d48538fa'
down_revision: str | Sequence[str] | None = '6451082f08e8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_ad_id', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_assessments_external_ad_id'), ['external_ad_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessments_external_ad_id'))
        batch_op.drop_column('external_ad_id')

    # ### end Alembic commands ###
