"""initial schema

Revision ID: 6451082f08e8
Revises: 
Create Date: 2026-09-06 11:32:43.812125

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# Custom column types referenced by autogenerated migrations.
import backend.app.infra.db.types  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '6451082f08e8'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', backend.app.infra.db.types.UtcDateTime(timezone=True), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('industry', sa.String(length=64), nullable=False),
    sa.Column('ad_type', sa.String(length=64), nullable=False),
    sa.Column('image_sha256', sa.String(length=64), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('scorecard', sa.JSON(), nullable=False),
    sa.Column('visual_analysis', sa.JSON(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('provider_info', sa.JSON(), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessments_cache_key'), ['cache_key'], unique=True)
        batch_op.create_index('ix_assessments_created_at_desc', [sa.literal_column('created_at DESC')], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_image_sha256'), ['image_sha256'], unique=False)

    op.create_table('brands',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', backend.app.infra.db.types.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('comparisons',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', backend.app.infra.db.types.UtcDateTime(timezone=True), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('industry', sa.String(length=64), nullable=False),
    sa.Column('ad_type', sa.String(length=64), nullable=False),
    sa.Column('ranked_assessment_ids', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('brand_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('created_at', backend.app.infra.db.types.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_documents_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_documents_content_sha256'), ['content_sha256'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_content_sha256'))
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_brand_id'))

    op.drop_table('knowledge_documents')
    op.drop_table('comparisons')
    op.drop_table('brands')
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessments_image_sha256'))
        batch_op.drop_index('ix_assessments_created_at_desc')
        batch_op.drop_index(batch_op.f('ix_assessments_cache_key'))

    op.drop_table('assessments')
    # ### end Alembic commands ###
